version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    versioning-strategy: "widen"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
