name: Release

on:
  release:
#    types: [published]

permissions:
  contents: read

env:
  PHAR_PATH: dist/desniff.phar

jobs:
  test:
    uses: ./.github/workflows/test.yml

  build-and-publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-

    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --prefer-dist --no-progress --no-dev

    - name: Cache PHAR
      id: phar-cache
      uses: actions/cache@v3
      with:
        path: ${{ env.PHAR_PATH }}
        key: ${{ runner.os }}-phar-${{ github.ref }}

    - name: Build PHAR
      id: phar
      uses: addnab/docker-run-action@v3
      with:
        image: backdevs/box:latest
        options: -v ${{ github.workspace }}:/app
        run: compile

    - name: Upload PHAR artifact
      uses: actions/upload-artifact@v3
      with:
        name: desniff.phar
        path: ${{ env.PHAR_PATH }}
